name: Tesco Scraper

on:
  schedule:
    - cron: "0 6 * * 1"  # every Monday at 6 AM UTC
  workflow_dispatch:    # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: 🧼 Run scraper
        run: |
          python scrape_tesco_prices.py

      - name: 💾 Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add tesco_prices.json
          git commit -m "🤖 Update Tesco prices (auto)" || echo "No changes to commit"
          git push